# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/design-system
    # Job steps
    steps:
      # Checkout the code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Setup node with version 16.x and NPM registry url
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      
      #- name: Setup upterm session
      #  env:
      #    CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      #  uses: lhotari/action-upterm@v1
      
      # set git config
      - name: Set git config to github-actions
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
     
     # Run yarn install to install project packages
      - name: Yarn
        run: yarn install --frozen-lockfile
    
      #- name: Setup upterm session
      #  env:
      #    CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      #  uses: lhotari/action-upterm@v1
      
      # yarn build to build the project
      - name: Build package
        run: yarn build
        
      - name: Build and run storybook
        env:
            CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: |
          npm run --silent build-storybook -- --output-dir /tmp/chromatic--1888-bWWVRAGr8LrR >/dev/null 2>&1
          npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN
          
        
      #- name: Publish to Chromatic
      #  uses: chromaui/action@v1
      #  # Chromatic GitHub Action options
      #  with:
      #    # 👇 Chromatic projectToken, refer to the manage page to obtain it.
      #    projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      #    #buildScriptName: build-storybook
